name: secret_sorcerer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  go_router: ^16.3.0
  firebase_auth: ^6.1.1
  google_fonts: ^6.3.2
  flame: ^1.33.0
  flame_audio: ^2.11.11
  cloud_firestore: ^6.0.3
  shared_preferences: ^2.2.2
  # hive: ^2.2.3  # removed: using Firebase for session storage
  # hive_flutter: ^1.1.0  # removed

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tome.png
    - assets/images/wizard_hat.png
    - assets/images/game-assets/board/
    - assets/textures/fog.png
    - assets/textures/fog2.png
    - assets/images/game-assets/board/charmCard.png
    - assets/images/game-assets/board/curseCard.png
    - assets/images/game-assets/board/yesCard.png
    - assets/images/game-assets/board/noCard.png
    - assets/audio/TavernMusic.wav
    - assets/audio/TavernLobbyMusic.wav
    - assets/audio/role_reveal.mp3
    - assets/audio/backButton.wav
    - assets/audio/card_pick_up.mp3
    - assets/audio/charmCast.wav
    - assets/audio/curseCast.wav
    - assets/audio/enterButton.wav
    - assets/audio/hostJoin.wav
    - assets/audio/paperRoll.mp3
    - assets/audio/TavernThemeMusic.wav
    - assets/audio/drawDiscard.wav
    - assets/images/trophy.png
    - assets/textures/fog.png
    - assets/textures/fog2.png
    - assets/textures/parchment.png
    - assets/logos/title_logo.png
    - assets/images/game-assets/board/deck.png
    - assets/images/game-assets/board/discard.png
    - assets/images/game-assets/board/background.png
    - assets/images/hats/undefined.png
    - assets/images/hats/hatDefault.png
    - assets/images/hats/hatBlue.png
    - assets/images/hats/hatPink.png
    - assets/images/hats/hatGreen.png
    - assets/images/avatars/avatarDefault.png
    - assets/images/avatars/avatarPink.png