name: secret_sorcerer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.0
  go_router: ^16.3.0
  firebase_auth: ^6.1.1
  google_fonts: ^6.3.2
  flame: ^1.33.0
  flame_audio: ^2.11.11
  cloud_firestore: ^6.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tome.png
    - assets/images/wizard_hat.png
    - assets/images/game-assets/board/
    - assets/textures/fog.png
    - assets/textures/fog2.png
    - assets/images/game-assets/board/charmCard.png
    - assets/images/game-assets/board/curseCard.png
    - assets/audio/TavernMusic.wav
    - assets/audio/TavernLobbyMusic.wav
    - assets/audio/role_reveal.mp3
